// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { EventsGeojsonEventsGeojsonGetData, EventsGeojsonEventsGeojsonGetErrors, EventsGeojsonEventsGeojsonGetResponses, GetEventEventsEventIdGetData, GetEventEventsEventIdGetErrors, GetEventEventsEventIdGetResponses, GetStatsStatsGetData, GetStatsStatsGetResponses, HealthHealthGetData, HealthHealthGetResponses, ListEventsEventsGetData, ListEventsEventsGetErrors, ListEventsEventsGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List Events
 */
export const listEventsEventsGet = <ThrowOnError extends boolean = false>(options?: Options<ListEventsEventsGetData, ThrowOnError>): RequestResult<ListEventsEventsGetResponses, ListEventsEventsGetErrors, ThrowOnError> => (options?.client ?? client).get<ListEventsEventsGetResponses, ListEventsEventsGetErrors, ThrowOnError>({ url: '/events', ...options });

/**
 * Events Geojson
 */
export const eventsGeojsonEventsGeojsonGet = <ThrowOnError extends boolean = false>(options?: Options<EventsGeojsonEventsGeojsonGetData, ThrowOnError>): RequestResult<EventsGeojsonEventsGeojsonGetResponses, EventsGeojsonEventsGeojsonGetErrors, ThrowOnError> => (options?.client ?? client).get<EventsGeojsonEventsGeojsonGetResponses, EventsGeojsonEventsGeojsonGetErrors, ThrowOnError>({ url: '/events/geojson', ...options });

/**
 * Get Event
 */
export const getEventEventsEventIdGet = <ThrowOnError extends boolean = false>(options: Options<GetEventEventsEventIdGetData, ThrowOnError>): RequestResult<GetEventEventsEventIdGetResponses, GetEventEventsEventIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetEventEventsEventIdGetResponses, GetEventEventsEventIdGetErrors, ThrowOnError>({ url: '/events/{event_id}', ...options });

/**
 * Get Stats
 */
export const getStatsStatsGet = <ThrowOnError extends boolean = false>(options?: Options<GetStatsStatsGetData, ThrowOnError>): RequestResult<GetStatsStatsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetStatsStatsGetResponses, unknown, ThrowOnError>({ url: '/stats', ...options });
