// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ArticleSummary
 */
export type ArticleSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Source Id
     */
    source_id?: string | null;
    /**
     * Source Type
     */
    source_type?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Published At
     */
    published_at?: string | null;
};

/**
 * DistributionItem
 */
export type DistributionItem = {
    /**
     * Label
     */
    label: string;
    /**
     * Count
     */
    count: number;
};

/**
 * EventDetail
 */
export type EventDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Action Forms
     */
    action_forms: Array<string>;
    /**
     * Thematic Fields
     */
    thematic_fields: Array<string>;
    /**
     * Channel
     */
    channel?: string | null;
    /**
     * Intensity
     */
    intensity?: string | null;
    /**
     * Summary El
     */
    summary_el?: string | null;
    /**
     * Summary En
     */
    summary_en?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
    /**
     * Region Code
     */
    region_code?: string | null;
    /**
     * Article Count
     */
    article_count: number;
    /**
     * Source Count
     */
    source_count: number;
    /**
     * First Seen
     */
    first_seen?: string | null;
    /**
     * Last Seen
     */
    last_seen?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Classification Confidence
     */
    classification_confidence?: {
        [key: string]: unknown;
    } | null;
    /**
     * Articles
     */
    articles?: Array<ArticleSummary>;
};

/**
 * EventSummary
 */
export type EventSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Action Forms
     */
    action_forms: Array<string>;
    /**
     * Thematic Fields
     */
    thematic_fields: Array<string>;
    /**
     * Channel
     */
    channel?: string | null;
    /**
     * Intensity
     */
    intensity?: string | null;
    /**
     * Summary El
     */
    summary_el?: string | null;
    /**
     * Summary En
     */
    summary_en?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
    /**
     * Region Code
     */
    region_code?: string | null;
    /**
     * Article Count
     */
    article_count: number;
    /**
     * Source Count
     */
    source_count: number;
    /**
     * First Seen
     */
    first_seen?: string | null;
    /**
     * Last Seen
     */
    last_seen?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * GeoJSONFeature
 */
export type GeoJsonFeature = {
    /**
     * Type
     */
    type?: string;
    geometry: GeoJsonGeometry;
    properties: GeoJsonProperties;
};

/**
 * GeoJSONFeatureCollection
 */
export type GeoJsonFeatureCollection = {
    /**
     * Type
     */
    type?: string;
    /**
     * Features
     */
    features: Array<GeoJsonFeature>;
};

/**
 * GeoJSONGeometry
 */
export type GeoJsonGeometry = {
    /**
     * Type
     */
    type?: string;
    /**
     * Coordinates
     */
    coordinates: Array<number>;
};

/**
 * GeoJSONProperties
 */
export type GeoJsonProperties = {
    /**
     * Id
     */
    id: string;
    /**
     * Action Forms
     */
    action_forms: Array<string>;
    /**
     * Thematic Fields
     */
    thematic_fields: Array<string>;
    /**
     * Channel
     */
    channel?: string | null;
    /**
     * Intensity
     */
    intensity?: string | null;
    /**
     * Summary En
     */
    summary_en?: string | null;
    /**
     * Article Count
     */
    article_count: number;
    /**
     * First Seen
     */
    first_seen?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Db
     */
    db: string;
};

/**
 * StatsResponse
 */
export type StatsResponse = {
    /**
     * Total Events
     */
    total_events: number;
    /**
     * Total Articles
     */
    total_articles: number;
    /**
     * By Action Form
     */
    by_action_form: Array<DistributionItem>;
    /**
     * By Thematic Field
     */
    by_thematic_field: Array<DistributionItem>;
    /**
     * By Channel
     */
    by_channel: Array<DistributionItem>;
    /**
     * By Intensity
     */
    by_intensity: Array<DistributionItem>;
    /**
     * By Region
     */
    by_region: Array<DistributionItem>;
    /**
     * By Date
     */
    by_date: Array<DistributionItem>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ListEventsEventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Action Form
         */
        action_form?: string | null;
        /**
         * Thematic Field
         */
        thematic_field?: string | null;
        /**
         * Channel
         */
        channel?: string | null;
        /**
         * Intensity
         */
        intensity?: string | null;
        /**
         * Region Code
         */
        region_code?: string | null;
        /**
         * Date From
         *
         * ISO 8601 date
         */
        date_from?: string | null;
        /**
         * Date To
         *
         * ISO 8601 date
         */
        date_to?: string | null;
        /**
         * Bbox
         *
         * west,south,east,north
         */
        bbox?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/events';
};

export type ListEventsEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsEventsGetError = ListEventsEventsGetErrors[keyof ListEventsEventsGetErrors];

export type ListEventsEventsGetResponses = {
    /**
     * Response List Events Events Get
     *
     * Successful Response
     */
    200: Array<EventSummary>;
};

export type ListEventsEventsGetResponse = ListEventsEventsGetResponses[keyof ListEventsEventsGetResponses];

export type EventsGeojsonEventsGeojsonGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Action Form
         */
        action_form?: string | null;
        /**
         * Thematic Field
         */
        thematic_field?: string | null;
        /**
         * Channel
         */
        channel?: string | null;
    };
    url: '/events/geojson';
};

export type EventsGeojsonEventsGeojsonGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventsGeojsonEventsGeojsonGetError = EventsGeojsonEventsGeojsonGetErrors[keyof EventsGeojsonEventsGeojsonGetErrors];

export type EventsGeojsonEventsGeojsonGetResponses = {
    /**
     * Successful Response
     */
    200: GeoJsonFeatureCollection;
};

export type EventsGeojsonEventsGeojsonGetResponse = EventsGeojsonEventsGeojsonGetResponses[keyof EventsGeojsonEventsGeojsonGetResponses];

export type GetEventEventsEventIdGetData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/events/{event_id}';
};

export type GetEventEventsEventIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventEventsEventIdGetError = GetEventEventsEventIdGetErrors[keyof GetEventEventsEventIdGetErrors];

export type GetEventEventsEventIdGetResponses = {
    /**
     * Successful Response
     */
    200: EventDetail;
};

export type GetEventEventsEventIdGetResponse = GetEventEventsEventIdGetResponses[keyof GetEventEventsEventIdGetResponses];

export type GetStatsStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetStatsStatsGetResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type GetStatsStatsGetResponse = GetStatsStatsGetResponses[keyof GetStatsStatsGetResponses];
