// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ArticleSummary
 */
export type ArticleSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Source Id
     */
    source_id?: string | null;
    /**
     * Source Type
     */
    source_type?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Published At
     */
    published_at?: string | null;
};

/**
 * BoundaryFeature
 */
export type BoundaryFeature = {
    /**
     * Type
     */
    type?: string;
    /**
     * Geometry
     */
    geometry: {
        [key: string]: unknown;
    };
    properties: BoundaryProperties;
};

/**
 * BoundaryFeatureCollection
 */
export type BoundaryFeatureCollection = {
    /**
     * Type
     */
    type?: string;
    /**
     * Features
     */
    features: Array<BoundaryFeature>;
};

/**
 * BoundaryProperties
 */
export type BoundaryProperties = {
    /**
     * Name
     */
    name: string;
    /**
     * Region Code
     */
    region_code?: string | null;
};

/**
 * ChoroplethResponse
 */
export type ChoroplethResponse = {
    /**
     * Indicator
     */
    indicator: string;
    /**
     * Values
     */
    values?: Array<ChoroplethValue>;
};

/**
 * ChoroplethValue
 */
export type ChoroplethValue = {
    /**
     * Region Code
     */
    region_code: string;
    /**
     * Value
     */
    value?: number | null;
    /**
     * Period
     */
    period?: string | null;
};

/**
 * DistributionItem
 */
export type DistributionItem = {
    /**
     * Label
     */
    label: string;
    /**
     * Count
     */
    count: number;
};

/**
 * EventContextResponse
 */
export type EventContextResponse = {
    /**
     * Region Code
     */
    region_code: string;
    /**
     * Always On
     */
    always_on?: Array<IndicatorValue>;
    /**
     * Thematic
     */
    thematic?: Array<IndicatorValue>;
};

/**
 * EventDetail
 */
export type EventDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Action Forms
     */
    action_forms: Array<string>;
    /**
     * Thematic Fields
     */
    thematic_fields: Array<string>;
    /**
     * Channel
     */
    channel?: string | null;
    /**
     * Intensity
     */
    intensity?: string | null;
    /**
     * Summary El
     */
    summary_el?: string | null;
    /**
     * Summary En
     */
    summary_en?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
    /**
     * Region Code
     */
    region_code?: string | null;
    /**
     * Municipality
     */
    municipality?: string | null;
    /**
     * Article Count
     */
    article_count: number;
    /**
     * Source Count
     */
    source_count: number;
    /**
     * First Seen
     */
    first_seen?: string | null;
    /**
     * Last Seen
     */
    last_seen?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Event Time
     */
    event_time?: string | null;
    /**
     * Temporal Status
     */
    temporal_status?: string | null;
    /**
     * Is National
     */
    is_national?: boolean;
    /**
     * Announced By
     */
    announced_by?: string | null;
    /**
     * Participating Unions
     */
    participating_unions?: Array<string>;
    /**
     * Classification Confidence
     */
    classification_confidence?: {
        [key: string]: unknown;
    } | null;
    /**
     * Articles
     */
    articles?: Array<ArticleSummary>;
};

/**
 * EventSummary
 */
export type EventSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Action Forms
     */
    action_forms: Array<string>;
    /**
     * Thematic Fields
     */
    thematic_fields: Array<string>;
    /**
     * Channel
     */
    channel?: string | null;
    /**
     * Intensity
     */
    intensity?: string | null;
    /**
     * Summary El
     */
    summary_el?: string | null;
    /**
     * Summary En
     */
    summary_en?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
    /**
     * Region Code
     */
    region_code?: string | null;
    /**
     * Municipality
     */
    municipality?: string | null;
    /**
     * Article Count
     */
    article_count: number;
    /**
     * Source Count
     */
    source_count: number;
    /**
     * First Seen
     */
    first_seen?: string | null;
    /**
     * Last Seen
     */
    last_seen?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Event Time
     */
    event_time?: string | null;
    /**
     * Temporal Status
     */
    temporal_status?: string | null;
    /**
     * Is National
     */
    is_national?: boolean;
    /**
     * Announced By
     */
    announced_by?: string | null;
    /**
     * Participating Unions
     */
    participating_unions?: Array<string>;
};

/**
 * GeoJSONFeature
 */
export type GeoJsonFeature = {
    /**
     * Type
     */
    type?: string;
    geometry: GeoJsonGeometry;
    properties: GeoJsonProperties;
};

/**
 * GeoJSONFeatureCollection
 */
export type GeoJsonFeatureCollection = {
    /**
     * Type
     */
    type?: string;
    /**
     * Features
     */
    features: Array<GeoJsonFeature>;
};

/**
 * GeoJSONGeometry
 */
export type GeoJsonGeometry = {
    /**
     * Type
     */
    type?: string;
    /**
     * Coordinates
     */
    coordinates: Array<number>;
};

/**
 * GeoJSONProperties
 */
export type GeoJsonProperties = {
    /**
     * Id
     */
    id: string;
    /**
     * Region Code
     */
    region_code?: string | null;
    /**
     * Municipality
     */
    municipality?: string | null;
    /**
     * Action Forms
     */
    action_forms: Array<string>;
    /**
     * Thematic Fields
     */
    thematic_fields: Array<string>;
    /**
     * Channel
     */
    channel?: string | null;
    /**
     * Intensity
     */
    intensity?: string | null;
    /**
     * Summary En
     */
    summary_en?: string | null;
    /**
     * Article Count
     */
    article_count: number;
    /**
     * First Seen
     */
    first_seen?: string | null;
    /**
     * Locations
     */
    locations?: Array<LocationPoint>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Db
     */
    db: string;
};

/**
 * IndicatorCatalogEntry
 */
export type IndicatorCatalogEntry = {
    /**
     * Key
     */
    key: string;
    /**
     * Label El
     */
    label_el: string;
    /**
     * Label En
     */
    label_en: string;
    /**
     * Unit
     */
    unit?: string | null;
};

/**
 * IndicatorCatalogResponse
 */
export type IndicatorCatalogResponse = {
    /**
     * Indicators
     */
    indicators?: Array<IndicatorCatalogEntry>;
};

/**
 * IndicatorValue
 */
export type IndicatorValue = {
    /**
     * Key
     */
    key: string;
    /**
     * Label El
     */
    label_el: string;
    /**
     * Label En
     */
    label_en: string;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Value
     */
    value?: number | null;
    /**
     * Period
     */
    period?: string | null;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
};

/**
 * LocationPoint
 */
export type LocationPoint = {
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Is Primary
     */
    is_primary: boolean;
};

/**
 * RegionIndicatorsResponse
 */
export type RegionIndicatorsResponse = {
    /**
     * Region Code
     */
    region_code: string;
    /**
     * Always On
     */
    always_on?: Array<IndicatorValue>;
    /**
     * Thematic
     */
    thematic?: Array<IndicatorValue>;
};

/**
 * StatsResponse
 */
export type StatsResponse = {
    /**
     * Total Events
     */
    total_events: number;
    /**
     * Total Articles
     */
    total_articles: number;
    /**
     * By Action Form
     */
    by_action_form: Array<DistributionItem>;
    /**
     * By Thematic Field
     */
    by_thematic_field: Array<DistributionItem>;
    /**
     * By Channel
     */
    by_channel: Array<DistributionItem>;
    /**
     * By Intensity
     */
    by_intensity: Array<DistributionItem>;
    /**
     * By Region
     */
    by_region: Array<DistributionItem>;
    /**
     * By Date
     */
    by_date: Array<DistributionItem>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ListEventsEventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Action Form
         */
        action_form?: string | null;
        /**
         * Thematic Field
         */
        thematic_field?: string | null;
        /**
         * Channel
         */
        channel?: string | null;
        /**
         * Intensity
         */
        intensity?: string | null;
        /**
         * Region Code
         */
        region_code?: string | null;
        /**
         * Municipality
         */
        municipality?: string | null;
        /**
         * Date From
         *
         * ISO 8601 date
         */
        date_from?: string | null;
        /**
         * Date To
         *
         * ISO 8601 date
         */
        date_to?: string | null;
        /**
         * Bbox
         *
         * west,south,east,north
         */
        bbox?: string | null;
        /**
         * Temporal Status
         */
        temporal_status?: 'upcoming' | 'today' | 'past' | null;
        /**
         * Is National
         */
        is_national?: boolean | null;
        /**
         * Order By
         */
        order_by?: 'recent' | 'event_time';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/events';
};

export type ListEventsEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsEventsGetError = ListEventsEventsGetErrors[keyof ListEventsEventsGetErrors];

export type ListEventsEventsGetResponses = {
    /**
     * Response List Events Events Get
     *
     * Successful Response
     */
    200: Array<EventSummary>;
};

export type ListEventsEventsGetResponse = ListEventsEventsGetResponses[keyof ListEventsEventsGetResponses];

export type EventsGeojsonEventsGeojsonGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Action Form
         */
        action_form?: string | null;
        /**
         * Thematic Field
         */
        thematic_field?: string | null;
        /**
         * Channel
         */
        channel?: string | null;
    };
    url: '/events/geojson';
};

export type EventsGeojsonEventsGeojsonGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventsGeojsonEventsGeojsonGetError = EventsGeojsonEventsGeojsonGetErrors[keyof EventsGeojsonEventsGeojsonGetErrors];

export type EventsGeojsonEventsGeojsonGetResponses = {
    /**
     * Successful Response
     */
    200: GeoJsonFeatureCollection;
};

export type EventsGeojsonEventsGeojsonGetResponse = EventsGeojsonEventsGeojsonGetResponses[keyof EventsGeojsonEventsGeojsonGetResponses];

export type GetEventEventsEventIdGetData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/events/{event_id}';
};

export type GetEventEventsEventIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventEventsEventIdGetError = GetEventEventsEventIdGetErrors[keyof GetEventEventsEventIdGetErrors];

export type GetEventEventsEventIdGetResponses = {
    /**
     * Successful Response
     */
    200: EventDetail;
};

export type GetEventEventsEventIdGetResponse = GetEventEventsEventIdGetResponses[keyof GetEventEventsEventIdGetResponses];

export type EventContextEventsEventIdContextGetData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/events/{event_id}/context';
};

export type EventContextEventsEventIdContextGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventContextEventsEventIdContextGetError = EventContextEventsEventIdContextGetErrors[keyof EventContextEventsEventIdContextGetErrors];

export type EventContextEventsEventIdContextGetResponses = {
    /**
     * Successful Response
     */
    200: EventContextResponse;
};

export type EventContextEventsEventIdContextGetResponse = EventContextEventsEventIdContextGetResponses[keyof EventContextEventsEventIdContextGetResponses];

export type GetStatsStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetStatsStatsGetResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type GetStatsStatsGetResponse = GetStatsStatsGetResponses[keyof GetStatsStatsGetResponses];

export type ListPeripheriesBoundariesPeripheriesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/boundaries/peripheries';
};

export type ListPeripheriesBoundariesPeripheriesGetResponses = {
    /**
     * Successful Response
     */
    200: BoundaryFeatureCollection;
};

export type ListPeripheriesBoundariesPeripheriesGetResponse = ListPeripheriesBoundariesPeripheriesGetResponses[keyof ListPeripheriesBoundariesPeripheriesGetResponses];

export type ListMunicipalitiesBoundariesMunicipalitiesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Periphery
         *
         * region_code of the parent periphery
         */
        periphery: string;
    };
    url: '/boundaries/municipalities';
};

export type ListMunicipalitiesBoundariesMunicipalitiesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMunicipalitiesBoundariesMunicipalitiesGetError = ListMunicipalitiesBoundariesMunicipalitiesGetErrors[keyof ListMunicipalitiesBoundariesMunicipalitiesGetErrors];

export type ListMunicipalitiesBoundariesMunicipalitiesGetResponses = {
    /**
     * Successful Response
     */
    200: BoundaryFeatureCollection;
};

export type ListMunicipalitiesBoundariesMunicipalitiesGetResponse = ListMunicipalitiesBoundariesMunicipalitiesGetResponses[keyof ListMunicipalitiesBoundariesMunicipalitiesGetResponses];

export type RegionIndicatorsRegionsRegionCodeIndicatorsGetData = {
    body?: never;
    path: {
        /**
         * Region Code
         */
        region_code: string;
    };
    query?: never;
    url: '/regions/{region_code}/indicators';
};

export type RegionIndicatorsRegionsRegionCodeIndicatorsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegionIndicatorsRegionsRegionCodeIndicatorsGetError = RegionIndicatorsRegionsRegionCodeIndicatorsGetErrors[keyof RegionIndicatorsRegionsRegionCodeIndicatorsGetErrors];

export type RegionIndicatorsRegionsRegionCodeIndicatorsGetResponses = {
    /**
     * Successful Response
     */
    200: RegionIndicatorsResponse;
};

export type RegionIndicatorsRegionsRegionCodeIndicatorsGetResponse = RegionIndicatorsRegionsRegionCodeIndicatorsGetResponses[keyof RegionIndicatorsRegionsRegionCodeIndicatorsGetResponses];

export type ChoroplethStatsChoroplethGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Indicator
         */
        indicator: string;
    };
    url: '/stats/choropleth';
};

export type ChoroplethStatsChoroplethGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChoroplethStatsChoroplethGetError = ChoroplethStatsChoroplethGetErrors[keyof ChoroplethStatsChoroplethGetErrors];

export type ChoroplethStatsChoroplethGetResponses = {
    /**
     * Successful Response
     */
    200: ChoroplethResponse;
};

export type ChoroplethStatsChoroplethGetResponse = ChoroplethStatsChoroplethGetResponses[keyof ChoroplethStatsChoroplethGetResponses];

export type IndicatorCatalogStatsIndicatorsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats/indicators';
};

export type IndicatorCatalogStatsIndicatorsGetResponses = {
    /**
     * Successful Response
     */
    200: IndicatorCatalogResponse;
};

export type IndicatorCatalogStatsIndicatorsGetResponse = IndicatorCatalogStatsIndicatorsGetResponses[keyof IndicatorCatalogStatsIndicatorsGetResponses];
